[SYSTEM]
# KabuStation の API パスワード
APIPW = "password"

[KABUS]
# KabuStation の実行ファイルパス
PATH = 'C:\Users\masay\AppData\Local\kabuStation\KabuS.exe'

[TRADEAPP]
# TradeWebApp の設定ファイルパス
CONF = 'S:\GitHub\masayoshi4649\KabuStationWebApp\app.toml'
# TradeWebApp の実行ファイルパス
PATH = 'S:\GitHub\masayoshi4649\KabuStationWebApp\KabuStationWebApp.exe'
